# Generated by Django 2.2.3 on 2020-08-10 04:45

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateField()),
                ('tags', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('creatorid', models.IntegerField()),
                ('tname', models.CharField(max_length=100)),
                ('uidlist', models.ManyToManyField(to='testapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('content', tinymce.models.HTMLField()),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Article')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.User')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.User'),
        ),
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isManager', models.BooleanField(default=False)),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Team')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.User')),
            ],
            options={
                'unique_together': {('tid', 'uid')},
            },
        ),
    ]
