# Generated by Django 2.2.3 on 2020-08-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.TextField(default=''),
        ),
    ]
