# Generated by Django 2.2.3 on 2020-08-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20200811_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uphoto',
            field=models.ImageField(default='uphoto/default.jpg', upload_to='uphoto/'),
        ),
    ]
